sudo: true
language: haskell

git:
  depth: 5

cabal: "3.2"

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
  - ghc: 8.10.3

install:
  - ghc --version
  - cabal --version
  - cabal new-update
  - cabal new-build --enable-tests --enable-benchmarks

script:
  - cabal new-test --enable-tests

notifications:
  email: false
